name: CI/CD

on:
    release:
        types: [published]
    push:
        branches:
            - master
            - gh-actions
    pull_request:
        types: [review_requested, ready_for_review]
        branches:
            - master
            - gh-actions

jobs:
    build:
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      **/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

            - name: Install dependencies
              run: npm i

            - name: Run the tests and generate coverage report
              run: npm run cov:actions
              env:
                  EMAIL: ${{ secrets.EMAIL }}
                  PASSWORD: ${{ secrets.PASSWORD }}

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1

            - name: Build docs
              run: npm run doc:html

            - name: Deploy draft to Netlify
              uses: South-Paw/action-netlify-deploy@v1.0.4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
                  build-dir: './build/docs'
                  draft: true
                  comment-on-commit: true
    docs:
        if: ${{ github.event_name == 'release' }}
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      **/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

            - name: Install dependencies
              run: npm i

            - name: Build docs
              run: npm run doc:html

            - name: Publish to netlify
              uses: South-Paw/action-netlify-deploy@v1.0.4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
                  build-dir: './build/docs'
                  comment-on-commit: true
